const theme = {
  space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
  sizes: {
    blogContainer: "675px",
    container: "1100px",
  },
  fonts: {
    body: "Roboto, sans-serif",
    heading: "Poppins, sans-serif",
    monospace: "Menlo, monospace",
  },
  fontSizes: [12, 14, 16, 20, 24, 32, 48, 64, 96],
  fontWeights: {
    body: 400,
    heading: 900,
    bold: 700,
  },
  lineHeights: {
    body: 1.6,
    heading: 1.25,
  },
  useColorSchemeMediaQuery: true,
  colors: {
    text: "#1a202c",
    background: "#f7fafc",
    primary: "#609",
    secondary: "#306",
    muted: "#f6f6f6",
    italic: "#5A6072",
    toggle: "hsl(230, 25%, 18%)",
    card: "#f7fafc",
    highlight: "#B5D5FF",
    warning: "rgb(255, 128, 0)",
    check: "green",
    info: "rgb(0, 133, 255)",
    warningBg: "rgb(255, 221, 0,.25)",
    checkBg: "rgb(0,204,136,0.1)",
    infoBg: "#DFEBF6",
    modes: {
      dark: {
        text: "hsl(210, 50%, 96%)",
        background: "hsl(230, 25%, 18%)",
        primary: "hsl(260, 100%, 80%)",
        secondary: "hsl(290, 100%, 80%)",
        highlight: "hsl(260, 20%, 40%)",
        accent: "hsl(290, 100%, 80%)",
        muted: "hsl(230, 20%, 0%, 20%)",
        gray: "hsl(210, 50%, 60%)",
        toggle: "#000",
        card: "hsl(230, 25%, 19%)",
        warningBg: "rgb(255,162,0,0.1)",
        checkBg: "rgb(0,204,136,0.2)",
        infoBg: "rgb(223, 235, 246,0.1)",
      },
    },
  },
  styles: {
    root: {
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "body",
    },
    h1: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 5,
    },
    h2: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 5,
      my: 4,
      scrollMarginTop: "128px",
      a: {
        float: "left",
        marginLeft: "-24px",
      },
      svg: {
        visibility: "hidden",
      },
      "&:hover": {
        svg: {
          visibility: "visible",
          height: "25px",
          width: "20px",
          fill: "highlight",
        },
      },
    },
    h3: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 3,
      my: 3,
      scrollMarginTop: "1em",
      a: {
        float: "left",
        marginLeft: "-24px",
      },
      svg: {
        visibility: "hidden",
      },
      "&:hover": {
        svg: {
          visibility: "visible",
          height: "25px",
          width: "20px",
          fill: "highlight",
        },
      },
    },
    h4: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 2,
      my: 2,
      scrollMarginTop: "128px",
    },
    h5: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 1,
    },
    h6: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 0,
    },
    p: {
      color: "text",
      fontSize: 3,
      fontFamily: "body",
      fontWeight: "body",
      lineHeight: "body",
      margin: "20px 0",
    },
    a: {
      color: "primary",
      overflowWrap: "break-word",
      wordWrap: "break-word",
      hyphens: "auto",
      "&::hover": {
        color: "highlight",
      },
      "&::focus": {
        color: "highlight",
      },
    },
    blockquote: {
      fontSize: "18px",
      borderLeftWidth: "5px",
      borderLeftColor: "primary",
      borderLeftStyle: "solid",
      backgroundColor: "highlight",
      padding: "0.5em 1rem",
      borderRadius: "4px",
      marginTop: 3,
    },
    hr: {
      my: 2,
    },
    ul: {
      listStyle: "square inside",
    },
    li: {
      // display:"",
      lineHeight: "body",
      marginTop: "1em",
    },
    svg: {
      stroke: "text",
    },
  },
}

export default theme
